"""Minimal initial wiki projection created with a new workspace."""

from __future__ import annotations

import hashlib
from datetime import datetime
from pathlib import Path

from linguawiki.clock import Clock, SystemClock, aware_utc, naive_utc
from linguawiki.db import migrations as migration_module
from linguawiki.db.connection import Database, open_writer
from linguawiki.errors import ErrorDetail, LinguaWikiError
from linguawiki.ids import EventId
from linguawiki.models import ContractModel
from linguawiki.paths import WIKI_DIRECTORIES, WorkspacePaths, assert_within
from linguawiki.services import errors as error_service
from linguawiki.services import estimates as estimate_service
from linguawiki.services import learners as learner_service
from linguawiki.services import sessions as session_service

PROJECTION_NAME = "wiki"
PROJECTION_VERSION = 1
GENERATED_NOTICE = "<!-- generated by linguawiki; do not edit by hand -->"


def _index_markdown(*, workspace_name: str, created_at: datetime) -> str:
    stamp = created_at.isoformat().replace("+00:00", "Z")
    return "\n".join(
        (
            GENERATED_NOTICE,
            "",
            f"# {workspace_name}",
            "",
            f"Initialized at {stamp}. This projection is generated from the learner database;",
            "it holds no learner content yet.",
            "",
            "## Sections",
            "",
            "- `learner/` — profile and progress summaries",
            "- `languages/` — target-language knowledge projections",
            "- `sessions/` — completed session summaries",
            "- `reports/` — weekly and monthly reports",
            "",
        )
    )


def write_initial_projection(
    paths: WorkspacePaths, *, workspace_name: str, created_at: datetime
) -> tuple[str, ...]:
    """Create the empty, privacy-safe wiki skeleton and return the written files."""

    for relative in WIKI_DIRECTORIES:
        directory = assert_within(paths.root / relative, paths.root, purpose="wiki directory")
        directory.mkdir(parents=True, exist_ok=True)
        keep = directory / ".gitkeep"
        if relative != "wiki" and not keep.exists():
            keep.write_text("", encoding="utf-8")
    index = paths.wiki / "index.md"
    index.write_text(
        _index_markdown(workspace_name=workspace_name, created_at=created_at), encoding="utf-8"
    )
    return tuple(
        sorted(
            path.relative_to(paths.root).as_posix()
            for path in paths.wiki.rglob("*")
            if path.is_file()
        )
    )


def projection_content_hash(root: Path) -> str:
    """Hash the rendered projection so drift is detectable from the database side."""

    digest = hashlib.sha256()
    for path in sorted((root / "wiki").rglob("*")):
        if not path.is_file():
            continue
        digest.update(path.relative_to(root).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\n")
    return digest.hexdigest()


# --- The dashboard projection ------------------------------------------------------
#
# A projection is a *rendering* of the database and never a second copy of it. Three
# rules follow, and all three are the reason this is a build command rather than a file
# the learner edits:
#
# - every generated page carries frontmatter saying so, plus the entity it is about, the
#   projection version, and the event the database had reached when it was written. A
#   reader can always tell what the page is and how old it is;
# - the projection's hash is stored in `projection_state`, so drift between the files
#   and the database is detectable from the database side. `session close` marks the
#   projection stale; only a build clears that;
# - a hand edit is not authoritative and never becomes state. It is overwritten by the
#   next build, which is what `wiki export-draft`/`import-draft` exist to avoid needing.
#
# The dashboard shows the learner's own errors as *patterns* -- category, signature,
# what each still needs -- and never their occurrence history, because that holds the
# words they actually said. A page under `wiki/` is the most-shared artifact in a
# workspace, so consent to retain a transcript is not consent to render one.

DASHBOARD_VIEWS: tuple[str, ...] = ("dashboard",)
#: How many rows of each kind the dashboard shows. A dashboard is a summary; the
#: commands behind it are where the whole list lives.
DASHBOARD_LIMIT = 8


class DashboardReport(ContractModel):
    """What a build wrote, and what the projection now claims to be."""

    view: str
    track_id: str
    files: tuple[str, ...] = ()
    projection_version: int = PROJECTION_VERSION
    content_hash: str
    source_event_id: str | None = None
    stale_before: bool = False
    generated_at: str
    warnings: tuple[str, ...] = ()


def _frontmatter(
    *,
    entity_id: str,
    source_event_id: str | None,
    generated_at: datetime,
) -> str:
    stamp = generated_at.isoformat().replace("+00:00", "Z")
    lines = [
        "---",
        "generated: true",
        f"entity_id: {entity_id}",
        f"projection_version: {PROJECTION_VERSION}",
        f"source_event_id: {source_event_id or 'none'}",
        f"generated_at: {stamp}",
        "---",
        "",
        GENERATED_NOTICE,
        "",
    ]
    return "\n".join(lines)


def _plan_section(report: session_service.SessionReport | None) -> list[str]:
    if report is None:
        return [
            "## Today's plan",
            "",
            "No session is planned. `linguawiki plan create --minutes <n>` makes one.",
            "",
        ]
    lines = [
        "## Today's plan",
        "",
        f"- Session `{report.session_id}` — **{report.status}**, {report.mode} mode, "
        f"{report.planned_minutes} of {report.requested_minutes} minute(s) planned",
        "",
        "| # | Block | Minutes | Objective | Status |",
        "|---:|---|---:|---|---|",
    ]
    lines.extend(
        f"| {block.sequence} | {block.block_type} | {block.planned_minutes} | "
        f"{block.objective} | {block.status} |"
        for block in report.blocks
    )
    lines.append("")
    if report.omissions:
        lines.append("Ranked and not scheduled:")
        lines.append("")
        lines.extend(
            f"- `{omission.block_type}` — {omission.reason}" for omission in report.omissions
        )
        lines.append("")
    if report.warnings:
        lines.append("Planner notes:")
        lines.append("")
        lines.extend(f"- {warning}" for warning in report.warnings)
        lines.append("")
    return lines


def _latest_session_section(report: session_service.SessionReport | None) -> list[str]:
    if report is None:
        return ["## Latest session", "", "No session has been closed yet.", ""]
    lines = [
        "## Latest session",
        "",
        f"- `{report.session_id}` — **{report.status}**"
        + (f", {report.actual_minutes} minute(s)" if report.actual_minutes else ""),
    ]
    close = report.finalization
    if close is not None:
        lines.append(
            f"- Recorded {close.attempts_written} attempt(s), {close.evidence_written} "
            f"evidence row(s), {close.errors_written} error occurrence(s), and "
            f"{close.followups_written} follow-up(s) from {close.staged_consumed} staged event(s)"
        )
        if close.stage_changes:
            lines.append("")
            lines.append("Stages that moved:")
            lines.append("")
            lines.extend(
                f"- `{change.content_id}` {change.stage_before or 'unseen'} → "
                f"**{change.stage_after}**"
                for change in close.stage_changes
            )
    elif report.staged_events:
        lines.append(
            f"- Holding {report.staged_events} staged event(s) that nothing has credited yet"
        )
    lines.append("")
    return lines


def _due_section(database: Database, *, track_id: str, now: datetime) -> list[str]:
    """Due retrieval and the open follow-up queue: what the next session owes."""

    items = database.query(
        "SELECT item.title, state.next_review_at, state.stage FROM track_item_state state "
        "JOIN knowledge_items item ON item.content_id = state.content_id "
        "WHERE state.track_id = ? AND state.next_review_at IS NOT NULL "
        "AND state.next_review_at <= ? ORDER BY state.next_review_at LIMIT ?",
        [track_id, naive_utc(now), DASHBOARD_LIMIT],
    )
    followups = error_service.followups(database, track_id=track_id, limit=DASHBOARD_LIMIT)
    lines = ["## Due work", ""]
    if not items and not followups:
        lines.extend(["Nothing is due.", ""])
        return lines
    if items:
        lines.append("Items due for retrieval:")
        lines.append("")
        lines.extend(
            f"- {title} — {stage}, due {aware_utc(due).date().isoformat()}"
            for title, due, stage in items
        )
        lines.append("")
    if followups:
        lines.append("Open follow-ups:")
        lines.append("")
        lines.extend(f"- {entry.kind}: {entry.action}" for entry in followups)
        lines.append("")
    return lines


def _errors_section(database: Database, *, track_id: str) -> list[str]:
    """Live error patterns. Categories and what each still needs -- never the history.

    The occurrence rows hold the learner's own words, and a page under `wiki/` is the
    most-shared thing in a workspace. Consent to retain a transcript is not consent to
    render one, so `include_history=False` is not a default here but the rule: the
    history stays behind `errors show`.
    """

    from linguawiki.error_model import LIVE_STATUSES

    placeholders = ", ".join("?" for _ in LIVE_STATUSES)
    identities = [
        str(error_id)
        for (error_id,) in database.query(
            f"SELECT error_id FROM error_patterns WHERE track_id = ? "
            f"AND status IN ({placeholders}) "
            "ORDER BY CASE severity WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END, "
            "occurrence_count DESC, last_seen_at DESC, error_id LIMIT ?",
            [track_id, *LIVE_STATUSES, DASHBOARD_LIMIT],
        )
    ]
    lines = ["## Active errors", ""]
    if not identities:
        lines.extend(["No live error patterns.", ""])
        return lines
    lines.extend(
        [
            "| Category | Status | Occurrences | Still needs |",
            "|---|---|---:|---|",
        ]
    )
    for identity in identities:
        entry = error_service.read_error(database, error_id=identity, include_history=False)
        outstanding = ", ".join(entry.outstanding) or "nothing: it is resolved"
        lines.append(
            f"| {entry.category} | {entry.status} | {entry.occurrence_count} | {outstanding} |"
        )
    lines.append("")
    return lines


def _estimates_section(database: Database, *, track_id: str) -> list[str]:
    """One estimate per dimension, each with its range and confidence.

    Never a single global level: a learner can be B1 in reading and A2 in speaking, and
    that difference is the useful part. `not-tested` is shown as what it is -- nobody
    measured it -- rather than as a low score.
    """

    records = estimate_service.read_estimates(database, track_id=track_id)
    lines = ["## Skill estimates", ""]
    if not records:
        lines.extend(["No estimate has been produced yet.", ""])
        return lines
    lines.extend(
        [
            "| Dimension | Status | Level | Range | Confidence | Evidence |",
            "|---|---|---|---|---|---:|",
        ]
    )
    for record in records:
        span = (
            "—"
            if record.level_low is None or record.level_high is None
            else f"{record.level_low} to {record.level_high}"
        )
        lines.append(
            f"| {record.dimension} | {record.estimate_status} | {record.level_code or '—'} | "
            f"{span} | {record.confidence_label} | {record.evidence_count} |"
        )
    lines.append("")
    return lines


def _dashboard_markdown(
    database: Database,
    *,
    track: learner_service.TrackRecord,
    plan: session_service.SessionReport | None,
    latest: session_service.SessionReport | None,
    now: datetime,
    source_event_id: str | None,
) -> str:
    sections = [
        _frontmatter(entity_id=track.track_id, source_event_id=source_event_id, generated_at=now),
        f"# {track.target_language} dashboard",
        "",
        f"Track `{track.track_id}` — declared {track.declared_level or 'unstated'}, "
        f"target {track.target_level or 'unstated'}, {track.proficiency_framework}.",
        "",
        "This page is generated from the learner database. Editing it changes nothing:",
        "the next `wiki build` overwrites it, and durable content is changed through",
        "`wiki export-draft` and `wiki import-draft`.",
        "",
    ]
    sections.extend(_plan_section(plan))
    sections.extend(_latest_session_section(latest))
    sections.extend(_due_section(database, track_id=track.track_id, now=now))
    sections.extend(_errors_section(database, track_id=track.track_id))
    sections.extend(_estimates_section(database, track_id=track.track_id))
    return "\n".join(sections)


def build(
    paths: WorkspacePaths,
    *,
    view: str = "dashboard",
    track: str | None = None,
    clock: Clock | None = None,
    command: str = "wiki.build",
) -> DashboardReport:
    """Render a generated view from the database, and record what was rendered.

    The write is the projection's own bookkeeping: the content hash and the event the
    database had reached. `session close` marks the projection stale; a build is the only
    thing that clears it, which is what makes "the wiki is behind the data" a question
    the database can answer.
    """

    if view not in DASHBOARD_VIEWS:
        raise LinguaWikiError(
            "unknown_wiki_view",
            f"this release renders {', '.join(DASHBOARD_VIEWS)}",
            details=(ErrorDetail(field="view", reason=view),),
        )
    active_clock = clock or SystemClock()
    with open_writer(paths, command=command, clock=active_clock) as database:
        track_id = learner_service.resolve_track(database, track)
        record = learner_service.track_context(database, track_id)
        now = aware_utc(database.now())
        stale_before = bool(
            database.scalar(
                "SELECT stale FROM projection_state WHERE projection = ?", [PROJECTION_NAME]
            )
        )
        source_event_id = database.scalar(
            "SELECT event_id FROM domain_events ORDER BY recorded_at DESC, event_id DESC LIMIT 1"
        )
        plan_id = database.scalar(
            "SELECT session_id FROM sessions WHERE track_id = ? "
            "AND status IN ('planned', 'active', 'closing') ORDER BY planned_at DESC LIMIT 1",
            [track_id],
        )
        latest_id = database.scalar(
            "SELECT session_id FROM sessions WHERE track_id = ? "
            "AND status IN ('completed', 'partial') ORDER BY closed_at DESC LIMIT 1",
            [track_id],
        )
        plan = (
            None
            if plan_id is None
            else session_service._read_session(database, session_id=str(plan_id))
        )
        latest = (
            None
            if latest_id is None
            else session_service._read_session(database, session_id=str(latest_id))
        )
        markdown = _dashboard_markdown(
            database,
            track=record,
            plan=plan,
            latest=latest,
            now=now,
            source_event_id=None if source_event_id is None else str(source_event_id),
        )
        directory = assert_within(paths.wiki / "learner", paths.root, purpose="wiki directory")
        directory.mkdir(parents=True, exist_ok=True)
        page = assert_within(directory / "dashboard.md", paths.root, purpose="wiki page")
        page.write_text(markdown, encoding="utf-8")
        content_hash = projection_content_hash(paths.root)
        with database.transaction() as transaction:
            transaction.execute(
                "UPDATE projection_state SET last_event_id = ?, content_hash = ?, "
                "stale = FALSE, generated_at = ?, updated_at = ? WHERE projection = ?",
                [
                    None if source_event_id is None else str(source_event_id),
                    content_hash,
                    naive_utc(now),
                    naive_utc(now),
                    PROJECTION_NAME,
                ],
            )
            migration_module.record_audit_entry(
                transaction,
                command=command,
                correlation_id=EventId.new(),
                outcome="succeeded",
                affected_records_json=f'["{PROJECTION_NAME}"]',
                before_summary="stale" if stale_before else "current",
                after_summary=f"rendered {view} for {track_id}",
            )
        return DashboardReport(
            view=view,
            track_id=track_id,
            files=(page.relative_to(paths.root).as_posix(),),
            content_hash=content_hash,
            source_event_id=None if source_event_id is None else str(source_event_id),
            stale_before=stale_before,
            generated_at=now.isoformat(),
            warnings=(
                () if plan is not None else ("no session is planned, so the plan section is empty",)
            ),
        )
